### ISSUE TITLE
Loss stops decreasing after two epochs

### ISSUE THREAD

**Issue by jlindsey15** [jramapuram/helpers#4]
Hi!  I have another question.  When I train the model, the loss saturates at exactly -0.125 after two epochs.  Any idea why this might happen?

![image](https://user-images.githubusercontent.com/2312795/85438419-fbd55380-b559-11ea-9e60-cc2f078f1210.png)

**Comment by jramapuram** [comment]
What are your training details? Easiest to probably paste the entire printed argparse here to debug.

**Comment by jramapuram** [comment]
Also note this is the wrong repo for this issue :)

**Comment by jlindsey15** [comment]
Yes, sorry about that!  I am closing this issue and will open one in the correct repo after a bit more debugging
